Enable cd
jenkinsci/antisamy-markup-formatter-plugin pull request #65
Opened 2022-01-11 09:21 UTC by batmat

This PR enables automated releases. 
See https://www.jenkins.io/doc/developer/publishing/releasing-cd/ for related documentation.

2022-01-11 10:09 UTC, timja commented on pom.xml
> +    <version>${revision}${changelist}</version>
This doesn’t look right, normally just use changelist

2022-01-11 13:50 UTC, jglick requested changes
https://www.jenkins.io/doc/developer/publishing/releasing-cd/#pom-file-modifications

https://github.com/jenkins-infra/jenkins-maven-cd-action/issues/15

2022-01-11 13:50 UTC, jglick commented on pom.xml
> +    <version>${revision}${changelist}</version>
```suggestion
    <version>${changelist}</version>
```

2022-01-11 13:50 UTC, jglick commented on pom.xml
> +        <changelist>-SNAPSHOT</changelist>
```suggestion
        <changelist>999999-SNAPSHOT</changelist>
```

2022-01-11 13:50 UTC, jglick commented on .mvn/maven.config
> +-Pmight-produce-incrementals
```suggestion
-Pmight-produce-incrementals
-Dchangelist.format=%d.v%s
```

2022-01-11 13:51 UTC, jglick commented
https://github.com/jenkins-infra/repository-permissions-updater/pull/2313 has been applied, good.

2022-01-12 09:20 UTC, batmat commented on pom.xml
> +    <version>${revision}${changelist}</version>
Applied.
Indeed I simply ran `mvn incrementals:incrementalify` but then got a bit confused by https://www.jenkins.io/doc/developer/publishing/releasing-cd/#pom-file-modifications I remember.

Would it be doable to have something akin to `mvn incrementals:enable-cd` or so to do this, you think?

2022-01-12 09:54 UTC, timja approved these changes

2022-01-12 13:51 UTC, jglick commented
> I simply ran mvn incrementals:incrementalify but then got a bit confused by https://www.jenkins.io/doc/developer/publishing/releasing-cd/#pom-file-modifications I remember.

Something we could do to make it clearer in docs that incrementalification is a _prerequisite_, on top of which you need to apply the described changes?

> Would it be doable to have something akin to mvn incrementals:enable-cd or so to do this, you think?

Perhaps.

2022-01-12 13:53 UTC, timja commented
> Something we could do to make it clearer in docs that incrementalification is a _prerequisite_, on top of which you need to apply the described changes?

https://www.jenkins.io/doc/developer/publishing/releasing-cd/#prerequisites ?

2022-01-12 13:53 UTC, jglick approved these changes

2022-01-12 13:53 UTC, jglick commented on pom.xml
> +      <tag>${scmTag}</tag>
```suggestion
        <tag>${scmTag}</tag>
```

Crappy indentation of XML (also `<xxx/>` ⇒ `<xxx />`) is a longstanding bug of the round-trip library bundled in `maven-release-plugin` used for the two junk commits per release, which would be superseded by this PR.

2022-01-12 16:51 UTC, merged